import { NextRequest, NextResponse } from "next/server";

const GROK_API_KEY = process.env.GROK_API_KEY || process.env.XAI_API_KEY || process.env.GROQ_API_KEY;
const GROK_BASE_URL = process.env.GROK_API_KEY || process.env.XAI_API_KEY
  ? "https://api.x.ai/v1"
  : "https://api.groq.com/openai/v1";

export async function POST(req: NextRequest) {
  try {
    const { company, topic } = await req.json();

    if (!GROK_API_KEY) {
      return NextResponse.json(
        { error: "Grok API key not configured" },
        { status: 500 }
      );
    }

    const prompt = `Generate one coding interview question that ${company} has been known to ask in recent interviews.
${topic ? `The question should be about ${topic}.` : ""}

Provide the response in this JSON format:
{
  "question": "the interview question text",
  "answer": "detailed explanation of the solution approach",
  "code": "code solution if applicable",
  "difficulty": "easy|medium|hard",
  "topic": "the topic category"
}

Make it realistic and specific to ${company}'s interview style. Only return the JSON.`;

    const response = await fetch(`${GROK_BASE_URL}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${GROK_API_KEY}`,
      },
      body: JSON.stringify({
        model: GROK_BASE_URL.includes("x.ai") ? "grok-2-latest" : "llama-3.3-70b-versatile",
        messages: [
          {
            role: "system",
            content: "You are an expert technical interviewer with knowledge of current interview trends at major tech companies.",
          },
          {
            role: "user",
            content: prompt,
          },
        ],
        temperature: 0.8,
        max_tokens: 2000,
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      console.error("Grok API error:", error);
      return NextResponse.json(
        { error: "Failed to generate question" },
        { status: 500 }
      );
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content || "";

    let question;
    try {
      const jsonMatch = content.match(/\{[\s\S]*\}/);
      const jsonStr = jsonMatch ? jsonMatch[0] : content;
      const parsed = JSON.parse(jsonStr);

      question = {
        id: `grok-${Date.now()}`,
        question: parsed.question,
        answer: parsed.answer,
        code: parsed.code,
        difficulty: parsed.difficulty?.toLowerCase() || "medium",
        topic: parsed.topic || topic || "General",
      };
    } catch (e) {
      question = {
        id: `grok-${Date.now()}`,
        question: content.substring(0, 500),
        answer: "Generated by Grok AI",
        difficulty: "medium",
        topic: topic || "General",
      };
    }

    return NextResponse.json({ question });
  } catch (error) {
    console.error("Error in Grok single API:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
