import { NextRequest, NextResponse } from "next/server";

const GROK_API_KEY = process.env.GROK_API_KEY || process.env.XAI_API_KEY || process.env.GROQ_API_KEY;
const GROK_BASE_URL = process.env.GROK_API_KEY || process.env.XAI_API_KEY
  ? "https://api.x.ai/v1"
  : "https://api.groq.com/openai/v1";

export async function POST(req: NextRequest) {
  try {
    const { company, topic, difficulty, count } = await req.json();

    if (!GROK_API_KEY) {
      return NextResponse.json(
        { error: "Grok API key not configured" },
        { status: 500 }
      );
    }

    const prompt = `Generate ${count} coding interview question(s) commonly asked at ${company}.
${topic ? `Focus on ${topic} topics.` : ""}
${difficulty !== "mixed" ? `Difficulty level: ${difficulty}.` : "Mix of easy, medium, and hard questions."}

For each question, provide:
1. The interview question
2. A detailed answer explanation
3. Code solution in a relevant programming language (if applicable)
4. Difficulty level (easy/medium/hard)
5. Topic category

Format your response as a JSON array with this structure:
[
  {
    "question": "string",
    "answer": "string",
    "code": "string (optional)",
    "difficulty": "easy|medium|hard",
    "topic": "string"
  }
]

Only return the JSON, no markdown formatting.`;

    const response = await fetch(`${GROK_BASE_URL}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${GROK_API_KEY}`,
      },
      body: JSON.stringify({
        model: GROK_BASE_URL.includes("x.ai") ? "grok-2-latest" : "llama-3.3-70b-versatile",
        messages: [
          {
            role: "system",
            content: "You are an expert technical interviewer who generates realistic coding interview questions based on company-specific interview patterns and latest trends.",
          },
          {
            role: "user",
            content: prompt,
          },
        ],
        temperature: 0.7,
        max_tokens: 4000,
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      console.error("Grok API error:", error);
      return NextResponse.json(
        { error: "Failed to generate questions" },
        { status: 500 }
      );
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content || "";

    // Parse the JSON response
    let questions = [];
    try {
      // Try to extract JSON from the response
      const jsonMatch = content.match(/\[[\s\S]*\]/);
      if (jsonMatch) {
        questions = JSON.parse(jsonMatch[0]);
      } else {
        questions = JSON.parse(content);
      }

      // Add unique IDs to each question
      questions = questions.map((q: any, index: number) => ({
        id: `grok-${Date.now()}-${index}`,
        question: q.question,
        answer: q.answer,
        code: q.code,
        difficulty: q.difficulty?.toLowerCase() || "medium",
        topic: q.topic || topic || "General",
      }));
    } catch (e) {
      console.error("Failed to parse Grok response:", e);
      // Return a fallback question if parsing fails
      questions = [{
        id: `grok-${Date.now()}-0`,
        question: content.substring(0, 500),
        answer: "Generated by Grok AI",
        difficulty: "medium",
        topic: topic || "General",
      }];
    }

    return NextResponse.json({ questions });
  } catch (error) {
    console.error("Error in Grok API:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
